title: LinZitong's Homepage
page-top-title: LinZitong（林姿彤）
top-section-bg-text: Be what you wanna be
home-subtitle: 林姿彤&ensp;| &ensp; INTJ
copyright-text: '&copy; Yourname 2023-2026. All Rights Reserved.'
site_name: LinZitong（林姿彤）
site_description: Computer Science
email: wing.zt.lin@gmail.com